###############################################################
#  Generated by:      Cadence Innovus 22.32-s080_1
#  OS:                Linux x86_64(Host ID seh-4.novalocal)
#  Generated on:      Wed Apr 10 13:19:36 2024
#  Design:            leon
#  Command:           create_clock_tree_spec -out ccopt.spec
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Common UI
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

if { [get_db clock_trees] != {} } {
  error {Cannot run clock tree spec: clock trees are already defined.}
}

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# The following pins are on the boundary of the STA clock network
# These pins are ignore skew pins
set_db pin:mcore0/a0/g1626/B .cts_sink_type ignore
set_db pin:mcore0/a0/g1626/B .cts_sink_type_reasons no_sdc_clock

# The following pins are clock sources
set_db pin:clk_div_reg/Q .cts_is_sdc_clock_root true
set_db port:clk .cts_is_sdc_clock_root true
set_db port:scan_clk .cts_is_sdc_clock_root true

# Clocks present at pin scan_clk
#   test_clk (period 8.000ns) in timing_config functional_func_slow_max([/home/Student-HN/Documents/Lab8.Cts_2/DBS_CUI/pre_cts.dat/mmmc/modes/functional_func_slow_max/functional_func_slow_max.sdc])
create_clock_tree -name test_clk -source scan_clk -no_skew_group
set_db clock_tree:test_clk .cts_clock_tree_source_max_capacitance 1.000
# Clock period setting for source pin of test_clk
set_db port:scan_clk .cts_clock_period 8

# Clocks present at pin clk
#   my_clk (period 4.000ns) in timing_config functional_func_slow_max([/home/Student-HN/Documents/Lab8.Cts_2/DBS_CUI/pre_cts.dat/mmmc/modes/functional_func_slow_max/functional_func_slow_max.sdc])
create_clock_tree -name my_clk -source clk -no_skew_group
set_db clock_tree:my_clk .cts_clock_tree_source_max_capacitance 1.000
# Clock period setting for source pin of my_clk
set_db port:clk .cts_clock_period 4

# Clocks present at pin clk_div_reg/Q
#   div_clk (period 8.000ns) in timing_config functional_func_slow_max([/home/Student-HN/Documents/Lab8.Cts_2/DBS_CUI/pre_cts.dat/mmmc/modes/functional_func_slow_max/functional_func_slow_max.sdc])
#   my_clk (period 4.000ns) in timing_config functional_func_slow_max([/home/Student-HN/Documents/Lab8.Cts_2/DBS_CUI/pre_cts.dat/mmmc/modes/functional_func_slow_max/functional_func_slow_max.sdc]) (generator)
create_generated_clock_tree -name div_clk -source clk_div_reg/Q -generated_by clk_div_reg/CK
# Clock period setting for source pin of div_clk
set_db pin:clk_div_reg/Q .cts_clock_period 8

##############################################################################
##
## Timing connectivity based skew groups: off
##
##############################################################################
set_db cts_timing_connectivity_info {}

# This is a -constrains "none" skew group (reporting only) for generated clock:div_clk in timing_config:functional_func_slow_max (sdc /home/Student-HN/Documents/Lab8.Cts_2/DBS_CUI/pre_cts.dat/mmmc/modes/functional_func_slow_max/functional_func_slow_max.sdc)
# because it corresponds to a generated clock that is synchronous to its master clock and will balanced as part of the skew group corresponding to one of its master clocks.
#  immediate master: clock:my_clk in timing_config functional_func_slow_max
#  balancing master: clock:my_clk in timing_config functional_func_slow_max
#   ultimate master: clock:my_clk in timing_config functional_func_slow_max
create_skew_group -name div_clk/functional_func_slow_max -sources clk_div_reg/Q -auto_sinks
set_db skew_group:div_clk/functional_func_slow_max .cts_skew_group_include_source_latency true
set_db skew_group:div_clk/functional_func_slow_max .cts_skew_group_constrains none
set_db skew_group:div_clk/functional_func_slow_max .cts_skew_group_created_from_clock div_clk
set_db skew_group:div_clk/functional_func_slow_max .cts_skew_group_created_from_constraint_modes {functional_func_slow_max  }
set_db skew_group:div_clk/functional_func_slow_max .cts_skew_group_created_from_delay_corners {slow_max fast_min}

# Skew group to balance non generated clock:my_clk in timing_config:functional_func_slow_max (sdc /home/Student-HN/Documents/Lab8.Cts_2/DBS_CUI/pre_cts.dat/mmmc/modes/functional_func_slow_max/functional_func_slow_max.sdc)
create_skew_group -name my_clk/functional_func_slow_max -sources clk -auto_sinks
set_db skew_group:my_clk/functional_func_slow_max .cts_skew_group_include_source_latency true
set_db skew_group:my_clk/functional_func_slow_max .cts_skew_group_created_from_clock my_clk
set_db skew_group:my_clk/functional_func_slow_max .cts_skew_group_created_from_constraint_modes {functional_func_slow_max  }
set_db skew_group:my_clk/functional_func_slow_max .cts_skew_group_created_from_delay_corners {slow_max fast_min}

# Skew group to balance non generated clock:test_clk in timing_config:functional_func_slow_max (sdc /home/Student-HN/Documents/Lab8.Cts_2/DBS_CUI/pre_cts.dat/mmmc/modes/functional_func_slow_max/functional_func_slow_max.sdc)
create_skew_group -name test_clk/functional_func_slow_max -sources scan_clk -auto_sinks
set_db skew_group:test_clk/functional_func_slow_max .cts_skew_group_include_source_latency true
set_db skew_group:test_clk/functional_func_slow_max .cts_skew_group_created_from_clock test_clk
set_db skew_group:test_clk/functional_func_slow_max .cts_skew_group_created_from_constraint_modes {functional_func_slow_max  }
set_db skew_group:test_clk/functional_func_slow_max .cts_skew_group_created_from_delay_corners {slow_max fast_min}


check_clock_tree_convergence
# Restore the ILM status if possible
if { [get_db ccopt_auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

